enum screen {
  MAIN
}

enum puppies {
  PUPPY,
  BOMB,
  HEAL
}

enum ESettings {
  PUPPY_STEP,
  PUPPY_UP_DURATION,
  PUPPY_DOWN_DURATION,
  PUPPY_UP_Y,
  PUPPY_DOWN_Y,
  PUPPY_INCREASE_ANIMATION_DURATION,
  PUPPY_BOMB_FLY_ANIMATION_DURATION,
  PUPPY_BOMB_FLY_ANIMATION_DELAY,

  PLAYER_JUMP_POINTS,
  PLAYER_SPEED,

  GAMEACTIONS_HEAL_CHANCE,
  GAMEACTIONS_PUPPY_CREATE_DELAY,
  GAMEACTIONS_PUPPY_NEW_GROUP_CREATE_DELAY,
  GAMEACTIONS_DAMAGE_ANIMATION_DURATION,
  GAMEACTIONS_MIN_GROUP_LENGTH,
  GAMEACTIONS_MAX_GROUP_LENGTH,
  GAMEACTIONS_EXPLOSION_ANIMATION_DURATION,
  GAMEACTIONS_EXPLOSION_DAMAGE,
  GAMEACTIONS_PUPPY_DAMAGE,

  TOWER_PADDING,
  ZONE_SWIPE_OFFSET,
  GAME_DIFFICULTY,

}

export {
  screen,
  ESettings,
  puppies
}